<?php
require_once '../config.php';

header('Content-Type: text/plain');
header('Content-Disposition: attachment; filename="courier_data_' . date('Y-m-d_H-i-s') . '.txt"');

if (!isAdminLoggedIn() && !isAgentLoggedIn()) {
    echo "Unauthorized access";
    exit;
}

try {
    $content = "FASTTRACK COURIER SERVICES - DATA EXPORT\n";
    $content .= "========================================\n";
    $content .= "Generated on: " . date('d M Y, h:i A') . "\n";
    $content .= "Generated by: " . (isAdminLoggedIn() ? 'Admin' : 'Agent') . "\n\n";

    if (isAdminLoggedIn()) {
        // Admin can export all data
        $stmt = $pdo->query("
            SELECT c.*, a.agent_name 
            FROM couriers c 
            LEFT JOIN agents a ON c.agent_id = a.agent_id 
            ORDER BY c.created_at DESC
        ");
        $content .= "COMPLETE COURIER DATA (ADMIN EXPORT)\n";
    } else {
        // Agent can export only their data
        $agent_id = $_SESSION['agent_agent_id'];
        $stmt = $pdo->prepare("
            SELECT c.*, a.agent_name 
            FROM couriers c 
            LEFT JOIN agents a ON c.agent_id = a.agent_id 
            WHERE c.agent_id = ?
            ORDER BY c.created_at DESC
        ");
        $stmt->execute([$agent_id]);
        $content .= "AGENT COURIER DATA EXPORT\n";
        $content .= "Agent ID: " . $agent_id . "\n";
    }
    
    $content .= "========================================\n\n";
    
    $couriers = $stmt->fetchAll();
    
    if (empty($couriers)) {
        $content .= "No courier data found.\n";
    } else {
        $content .= "Total Records: " . count($couriers) . "\n\n";
        
        foreach ($couriers as $index => $courier) {
            $content .= "RECORD #" . ($index + 1) . "\n";
            $content .= "----------------------------------------\n";
            $content .= "Courier ID: " . $courier['courier_id'] . "\n";
            $content .= "Party Name: " . $courier['party_name'] . "\n";
            $content .= "Mobile: " . $courier['mobile'] . "\n";
            $content .= "From City: " . $courier['from_city'] . "\n";
            $content .= "To City: " . $courier['to_city'] . "\n";
            $content .= "Amount: ₹" . number_format($courier['amount'], 2) . "\n";
            $content .= "Status: " . ucfirst($courier['status']) . "\n";
            $content .= "Agent: " . ($courier['agent_name'] ?? 'N/A') . "\n";
            $content .= "Created Date: " . date('d M Y, h:i A', strtotime($courier['created_at'])) . "\n";
            
            if ($courier['delivery_person']) {
                $content .= "Delivery Person: " . $courier['delivery_person'] . "\n";
            }
            
            if ($courier['remarks']) {
                $content .= "Remarks: " . $courier['remarks'] . "\n";
            }
            
            $content .= "Address: " . $courier['address'] . "\n";
            $content .= "\n";
        }
        
        // Add summary statistics
        $content .= "\nSUMMARY STATISTICS\n";
        $content .= "==================\n";
        
        $pending = array_filter($couriers, function($c) { return $c['status'] === 'pending'; });
        $in_transit = array_filter($couriers, function($c) { return $c['status'] === 'in_transit'; });
        $delivered = array_filter($couriers, function($c) { return $c['status'] === 'delivered'; });
        $cancelled = array_filter($couriers, function($c) { return $c['status'] === 'cancelled'; });
        
        $content .= "Pending: " . count($pending) . "\n";
        $content .= "In Transit: " . count($in_transit) . "\n";
        $content .= "Delivered: " . count($delivered) . "\n";
        $content .= "Cancelled: " . count($cancelled) . "\n";
        
        $total_amount = array_sum(array_column($couriers, 'amount'));
        $content .= "Total Business: ₹" . number_format($total_amount, 2) . "\n";
        
        $delivered_amount = array_sum(array_column($delivered, 'amount'));
        $content .= "Delivered Business: ₹" . number_format($delivered_amount, 2) . "\n";
    }
    
    $content .= "\n========================================\n";
    $content .= "End of Report\n";
    $content .= "FastTrack Courier Services\n";
    $content .= "Contact: +91 98765 43210\n";
    
    echo $content;
    
} catch (Exception $e) {
    echo "Error generating export: " . $e->getMessage();
}
?>